[workspace]
authors = ["Bror Jonsson <brorfred@gmail.com>"]
channels = ["conda-forge"]
description = "Cruise support package"
name = "seastate"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.0,<3"
scipy = ">=1.16.3,<2"
xarray = ">=2025.12.0,<2026"
pandas = ">=2.3.3,<3"
pytables = ">=3.10.2,<4"
zarr = ">=3.1.5,<4"
ipython = ">=9.9.0,<10"
matplotlib = ">=3.10.8,<4"
scikit-learn = ">=1.8.0,<2"
eumdac = ">=3.1.1,<4"
rasterio = ">=1.5.0,<2"
rio-tiler = ">=8.0.5,<9"
mercantile = ">=1.2.1,<2"
pillow = ">=12.1.0,<13"
netcdf4 = ">=1.7.3,<2"
satpy = ">=0.59.0,<0.60"
pyresample = ">=1.35.0,<2"
tinydb = ">=4.8.2,<5"
fsspec = ">=2025.12.0,<2026"
dynaconf = ">=3.2.12,<4"
copernicusmarine = ">=2.2.5,<3"
folium = ">=0.20.0,<0.21"
tqdm = ">=4.67.1,<5"
sysrsync = ">=1.1.1,<2"
pytest = ">=9.0.2,<10"
cmap = ">=0.7.0,<0.8"
cmasher = ">=1.9.2,<2"
typer = ">=0.21.1,<0.22"

[pypi-dependencies]
seastate = { path = ".", editable = true }
mkdocs = ">=1.5.0"
mkdocs-material = ">=9.4.0"
mkdocstrings = { version = ">=0.24.0", extras = ["python"] }
